{
    'name': 'Barangay Management Information System (Basic)',
    'version': '2.0.0',
    'category': 'Government',
    'author': 'AMB BS',
    'summary': 'Manage Barangay Residents and Services',
    'description': """Helps manage barangay basic residents profile""",
    'depends': ['base', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/resident_views.xml',
        'views/menu_views.xml',
    ],
    'demo': [],
    'images': ['static/description/banner.gif'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
